[project]
name = "clts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.6.0",
    "einops>=0.8.1",
    "torch>=2.7.0",
    "transformer-lens>=2.15.0",
]
